<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9puSdSg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9puSdSg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9puSdSg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9puSdSg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9puSdSg\App_KernelDevDebugContainer([
    'container.build_hash' => '9puSdSg',
    'container.build_id' => 'bd6bab3d',
    'container.build_time' => 1641302614,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9puSdSg');
