<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUlloV0R\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUlloV0R/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUlloV0R.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUlloV0R\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUlloV0R\App_KernelDevDebugContainer([
    'container.build_hash' => 'UlloV0R',
    'container.build_id' => 'e4a72a0b',
    'container.build_time' => 1641224512,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUlloV0R');
