<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYsTYp8I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYsTYp8I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYsTYp8I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYsTYp8I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYsTYp8I\App_KernelDevDebugContainer([
    'container.build_hash' => 'YsTYp8I',
    'container.build_id' => '91c0cc95',
    'container.build_time' => 1641289216,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYsTYp8I');
